services:
  carla:
    image: rdmchr/carlabot:latest
    restart: unless-stopped
    container_name: carla
    networks:
        - carla
    environment:
      - DISCORD_TOKEN=
      - JWA_ID=
      - JWA_SECRET=
      - DATABASE_URL="postgresql://postgres:postgres@postgres:5432/postgres?schema=public"
      - HETZNER_TOKEN=""
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: --interval 10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    networks:
      - carla
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  carla: