#cloud-config

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [ docker ]

runcmd:
  - [ wget, "https://gist.githubusercontent.com/rdmchr/943a77579c4989ba9537ebe5ee4da9f2/raw/63bc3683e91ce62c6ce0820f2e6e5e1e0ae94d67/docker-compose.yml", -O, /run/docker-compose.yml ]
  - sed -i 's/MY_POSTGRES_PASSWORD/REPLACE_WITH_PASSWORD/g' /run/docker-compose.yml
  - [ docker, compose, -f, "/run/docker-compose.yml", up, -d ]