services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_DB=postgres
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"